[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "cyclozarin"
name = "SnoringWarning"
description = "Mod for Content Warning that adds silly snoring sound when player is asleep"
websiteUrl = "https://github.com/cyclozarin/SnoringWarning"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Hamunii-AutoHookGenPatcher = "1.0.2"
RugbugRedfern-MyceliumNetworking = "1.0.11"
CommanderCat101-ContentSettings = "1.1.0"

[build]
icon = "icon.png"
readme = "../../README.md"
outdir = "../dist"

[[build.copy]]
source = "../bin/Release/netstandard2.1/zarin.contentwarning.snoringwarning.dll"
target = "/BepInEx/plugins/SnoringWarning/"

[publish]
communities = [ "content-warning" ]
[publish.categories]
content-warning = [ "audio", "mods" ]
# For a list of valid tags, look at the slug values in https://thunderstore.io/api/experimental/community/content-warning/category/
